apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: dev-grupo3-project
spec:
  name: "DEV-GRUPO3-PROJECT"
  projectIpAccessList:
    - ipAddress: "0.0.0.0/0"
      comment: "Allowing access to database from everywhere (only for Demo!)"

