version: "3.1"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
        MONGO_INITDB_ROOT_PASSWORD:root_password
    ports:
      - 27017:27017
      
      # Use root/example as user/password credentials

